config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  devise_for :users

  root "stories#index"
  resources :stories, param: :code, path: 's' do
    resources :chapters, param: :number, path: 'c', except: :index
    resources :blobs, path: 'b', except: [:index, :show]
  end
  match '/write', to: 'dashboard#index', via: 'get'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/blob.rb
class Blob < ApplicationRecord
  include Embedding

  belongs_to :story

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 2000}
end

app/controllers/blobs_controller.rb
class BlobsController < ApplicationController
  def new
    @blob = @user.stories.find_by!(code: params[:story_code]).blobs.new
    @back_url = edit_story_path(@blob.story.code)
  end

  def create
    story = @user.stories.find_by!(code: params[:story_code])
    @blob = story.blobs.new(blob_params)
    if @blob.save
      redirect_to edit_story_blob_path(story.code, @blob.id)
    else
      @back_url = edit_story_path(@blob.story.code)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @blob = get_blob
    @back_url = edit_story_path(@blob.story.code)
  end

  def update
    @blob = get_blob
    if @blob.update(blob_params)
      redirect_to edit_story_blob_path(@blob.story.code, @blob.id)
    else
      @back_url = edit_story_path(@blob.story.code)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    blob = get_blob
    blob.destroy
    redirect_to edit_story_path(blob.story.code)
  end

  private

  def get_blob
    Blob.joins(:story)
      .joins("JOIN users ON users.id = stories.author_id")
      .where(stories: {code: params[:story_code]})
      .where(blobs: {id: params[:id]})
      .where(users: {id: @user.id})
      .first!
  end

  def blob_params
    params.require(:blob).permit(:title, :body)
  end
end

app/helpers/blobs_helper.rb
module BlobsHelper
end

app/views/blobs/_form.html.erb
<%= form_with model: blob, url: url do |form| %>
  <p>tips:</p>
  <small>
    <ul>
      <li>keep each blob focused on one topic; it's better to have 3 blobs about 3 different things, than 1 blob about 3 things!</li>
      <li>don't put any information you don't want users to be able to find out by asking! e.g. the culprit's name</li>
    </ul>
  </small>
  <br>
  <div>
    <%= form.label :title %>
    <small>(this is for your reference only)</small>
    <br>
    <%= form.text_field :title %>
    <% blob.errors.full_messages_for(:title).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.label :body %>
    <br>
    <%= form.text_area :body %>
    <% blob.errors.full_messages_for(:body).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blobs/edit.html.erb
<h2><%= @blob.story.title %></h2>
<h3><%= @blob.title %></h3>
<p><%= @blob.body %></p>
<hr>
<%= render "form", blob: @blob, url: story_blob_path(@blob.story.code, @blob.id) %>
<br>
<br>
<h4>delete?</h4>
<div>
  <%= link_to("delete blob", story_blob_path(@blob.story.code, @blob.id), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  }) %>
</div>

app/views/blobs/new.html.erb
<h2><%= @blob.story.title %></h2>
<h4>New blob</h4>
<%= render "form", blob: @blob, url: story_blobs_path(@blob.story.code) %>