config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  devise_for :users

  root "stories#index"
  resources :stories, param: :code, path: 's' do
    resources :chapters, param: :number, path: 'c', except: :index
    resources :blobs, path: 'b', except: [:index, :show]
  end
  match '/write', to: 'dashboard#index', via: 'get'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :chapters, dependent: :destroy
  has_many :blobs, dependent: :destroy
  belongs_to :author, class_name: 'User'

  before_validation :generate_unique_code, on: :create

  validates :title, presence: true
  validates :summary, presence: true
  validates :code, presence: true, uniqueness: true

  def last_chapter
    self.chapters.order(number: :desc).first
  end

  private

  def generate_unique_code
    loop do
      self.code = SecureRandom.hex(3)
      break unless Story.exists?(code: self.code)
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @stories = Story.all.order(updated_at: :desc)
  end

  def show
    @story = Story.find_by!(code: params[:code])
    @back_url = root_path
  end

  def new
    @story = @user.stories.new
    @back_url = write_path
  end

  def create
    story = @user.stories.new(story_params)
    if story.save
      redirect_to edit_story_path(story.code)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @story = @user.stories.find_by!(code: params[:code])
    @back_url = write_path
  end

  def update
    story = @user.stories.find_by!(code: params[:code])
    if story.update(story_params)
      redirect_to edit_story_path(story.code)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    story = @user.stories.find_by!(code: params[:code])
    story.destroy
    redirect_to '/write', status: :see_other
  end

  private

  def story_params
    params.require(:story).permit(:title, :summary)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with model: story, url: url do |form| %>
  <div>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
    <% story.errors.full_messages_for(:title).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.label :summary %>
    <br>
    <%= form.text_area :summary %>
    <% story.errors.full_messages_for(:summary).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h2><%= @story.title %></h2>
<p><%= @story.summary %></p>
<hr>
<%= render "form", story: @story, url: story_path(@story.code) %>
<br>
<h4>chapters</h4>
<ul class="list-group list-group-flush">
  <% @story.chapters.order(number: :asc).each do |chapter| %>
    <li class="list-group-item">
      <%= link_to "#{chapter.number}: #{chapter.title}", edit_story_chapter_path(@story.code, chapter.number)%>
      <% if chapter.next.nil? %>
        <small>
          <%= link_to("[x]", story_chapter_path(@story.code, chapter.number), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
          }) %>
        </small>
      <% end %>
    </li>
  <% end %>
  <li class="list-group-item"><strong><%= link_to("write new chapter", new_story_chapter_path(@story.code)) %></strong></li>
</ul>
<br>
<h4>blobs</h4>
<small>blobs are pieces of information readers can't see but the chatbot can use to answer questions about the world!<br>
e.g. character profiles, past events, information about specific places or establishments, anything you want the chatbot to know!</small>
<ul class="list-group list-group-flush">
  <% @story.blobs.each do |blob| %>
    <li class="list-group-item">
      <%= link_to blob.title, edit_story_blob_path(@story.code, blob.id)%>
      <small>
        <%= link_to("[x]", story_blob_path(@story.code, blob.id), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        }) %>
      </small>
    </li>
  <% end %>
  <li class="list-group-item"><strong><%= link_to("create new blob", new_story_blob_path(@story.code)) %></strong></li>
</ul>
<br>
<h4>delete?</h4>
<div>
  <%= link_to("delete story", story_path(@story.code), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  }) %>
</div>

app/views/stories/index.html.erb
<p><strong>Welcome to fiction.party!</strong> You can read stories here... with a <i>twist</i>. At the end of every chapter,
  dive deeper into the world by chatting directly with the story! Find out more about a mysterious character, past
  incidents or just learning more about the everyday life of the townspeople!</p>

<p>...or create your own world with deep and rich lore! The world is your oyster!</p>
<br>
<h3>recently updated</h3>
<ul class="list-group list-group-flush">
  <% @stories.each do |story| %>
    <li class="list-group-item">
      <%= link_to story.title, story_path(story.code)%> <small class="text-muted">by <%= story.author.username %></small>
    </li>
  <% end %>
</ul>

app/views/stories/new.html.erb
<h4>New story</h4>
<%= render "form", story: @story, url: stories_path %>

app/views/stories/show.html.erb
<h2><%= @story.title %></h2>
<p class="small text-muted"><%= @story.author.username %></p>
<p><%= @story.summary %></p>
<h4>chapters</h4>
<ul class="list-group list-group-flush">
  <% @story.chapters.order(number: :asc).each do |chapter| %>
    <li class="list-group-item">
      <%= link_to("#{chapter.number}: #{chapter.title}", story_chapter_path(@story.code, chapter.number)) %>
    </li>
  <% end %>
</ul>