config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  devise_for :users

  root "stories#index"
  resources :stories, param: :code, path: 's' do
    resources :chapters, param: :number, path: 'c', except: :index
    resources :blobs, path: 'b', except: [:index, :show]
  end
  match '/write', to: 'dashboard#index', via: 'get'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  include Embedding

  has_many :chats, dependent: :destroy

  belongs_to :story

  before_validation :add_chapter_number, on: :create
  before_destroy :can_destroy?

  validates :number, presence: true, uniqueness: {scope: :story_id}
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 5000}

  def prev
    Chapter.find_by(story_id: story_id, number: number-1)
  end
  def next
    Chapter.find_by(story_id: story_id, number: number+1)
  end

  private

  def add_chapter_number
    last_chapter = story.last_chapter
    self.number = last_chapter.nil? ? 1 : last_chapter.number+1
  end

  def can_destroy?
    if number != story.last_chapter.number
      self.errors.add(:base, "can only delete the last chapter")
      raise InvalidDestroyCall.new("can only delete the last chapter")
    end
  end
end

class InvalidDestroyCall < StandardError
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @chapter = Chapter.joins(:story)
                      .where(stories: {code: params[:story_code]})
                      .where(chapters: {number: params[:number]})
                      .first!
    @prev = @chapter.prev
    @next = @chapter.next
    @back_url = story_path(@chapter.story.code)
    @cable_url = action_cable_url

    @chat_history = []
    if user_signed_in?
      chat = Chat.create_or_find_by!(chapter: @chapter, user: @user)
      chat.get_history.each do |message|
        @chat_history << ChatsChannel::Message.new(
          chat_message: message,
          user: message.user,
        )
      end
    end
  end

  def new
    @chapter = @user.stories.find_by!(code: params[:story_code]).chapters.new
    @back_url = edit_story_path(@chapter.story.code)
  end

  def create
    ActiveRecord::Base.transaction do
      story = @user.stories.find_by!(code: params[:story_code])
      @chapter = story.chapters.new(chapter_params)
      if @chapter.save
        redirect_to edit_story_chapter_path(story.code, @chapter.number)
      else
        @back_url = edit_story_path(@chapter.story.code)
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
    @chapter = get_chapter
    @back_url = edit_story_path(@chapter.story.code)
  end

  def update
    @chapter = get_chapter
    if @chapter.update(chapter_params)
      redirect_to edit_story_chapter_path(@chapter.story.code, @chapter.number)
    else
      @back_url = edit_story_path(@chapter.story.code)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    ActiveRecord::Base.transaction do
      @chapter = get_chapter
      begin
        @chapter.destroy
        redirect_to edit_story_path(@chapter.story.code)
      rescue InvalidDestroyCall
        @back_url = edit_story_path(@chapter.story.code)
        render :edit, status: :bad_request
      end
    end
  end

  private

  def get_chapter
    Chapter.joins(:story)
           .joins("JOIN users ON users.id = stories.author_id")
           .where(stories: {code: params[:story_code]})
           .where(chapters: {number: params[:number]})
           .where(users: {id: @user.id})
           .first!
  end

  def chapter_params
    params.require(:chapter).permit(:title, :body)
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_with model: chapter, url: url do |form| %>
  <div>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
    <% chapter.errors.full_messages_for(:title).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.label :body %>
    <br>
    <%= form.text_area :body %>
    <% chapter.errors.full_messages_for(:body).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h2><%= @chapter.story.title %></h2>
<h3><%= @chapter.number %>: <%= @chapter.title %></h3>
<p><%= @chapter.body %></p>
<hr>
<%= render "form", chapter: @chapter, url: story_chapter_path(@chapter.story.code, @chapter.number) %>
<% if @chapter.next.nil? %>
  <br>
  <br>
  <div>
    <h4>delete?</h4>
    <%= link_to("delete chapter", story_chapter_path(@chapter.story.code, @chapter.number), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }) %>
  </div>
<% end %>

app/views/chapters/new.html.erb
<h2><%= @chapter.story.title %></h2>
<h4>New chapter</h4>
<%= render "form", chapter: @chapter, url: story_chapters_path(@chapter.story.code) %>

app/views/chapters/show.html.erb
<h2><%= @chapter.story.title %></h2>
<h3><%= @chapter.number %>: <%= @chapter.title %></h3>
<p><%= @chapter.body %></p>
<br>
<br>
<h4>Chat</h4>
<% if @user %>
  <p>Ask questions and find out more about the world!</p>
  <div
    data-react-component="ChatWindow"
    data-props="<%= {'user': @user, 'chapter_id': @chapter.id, 'chat_history': @chat_history, 'cable_url': @cable_url }.to_json %>"
  ></div>
<% else %>
  <p>Login to explore the world of the story!</p>
<% end %>
<br>
<div>
  <% if @prev %>
    <%= link_to "prev", story_chapter_path(@prev.story.code, @prev.number) %>
  <% else %>
    prev
  <% end %>
  |
  <% if @next %>
    <%= link_to "next", story_chapter_path(@next.story.code, @next.number) %>
  <% else %>
    next
  <% end %>
</div>